// ============================================================
//  学習コンテンツ (私が生成 / 追加はこの配列に足すだけ)
//  レベル: 英検2級の上 〜 準1級中心
// ============================================================

// ---- 単語 (Vocabulary) ----
// term: 英単語 / pos: 品詞 / jp: 意味 / ex: 例文 / exJp: 例文訳
const VOCAB = [
  { id:"v001", term:"accomplish", pos:"v.", jp:"成し遂げる", ex:"She accomplished her goal in three years.", exJp:"彼女は3年で目標を成し遂げた。" },
  { id:"v002", term:"acknowledge", pos:"v.", jp:"認める、認識する", ex:"He acknowledged that he was wrong.", exJp:"彼は自分が間違っていたと認めた。" },
  { id:"v003", term:"adequate", pos:"adj.", jp:"十分な、適切な", ex:"The salary is adequate for my needs.", exJp:"その給料は私の必要には十分だ。" },
  { id:"v004", term:"anticipate", pos:"v.", jp:"予期する、見込む", ex:"We anticipate a rise in sales next month.", exJp:"来月は売上の増加を見込んでいる。" },
  { id:"v005", term:"apparent", pos:"adj.", jp:"明らかな、見かけ上の", ex:"It was apparent that she was tired.", exJp:"彼女が疲れているのは明らかだった。" },
  { id:"v006", term:"appreciate", pos:"v.", jp:"感謝する、正しく理解する", ex:"I really appreciate your help.", exJp:"あなたの助けに本当に感謝します。" },
  { id:"v007", term:"appropriate", pos:"adj.", jp:"適切な、ふさわしい", ex:"That's not appropriate for a formal meeting.", exJp:"それは正式な会議にはふさわしくない。" },
  { id:"v008", term:"assume", pos:"v.", jp:"想定する、思い込む", ex:"I assumed you already knew.", exJp:"あなたはもう知っていると思っていた。" },
  { id:"v009", term:"assure", pos:"v.", jp:"保証する、断言する", ex:"I assure you it will be ready on time.", exJp:"時間通りに準備できると保証します。" },
  { id:"v010", term:"attempt", pos:"v./n.", jp:"試みる、試み", ex:"He made an attempt to fix it himself.", exJp:"彼は自分で直そうと試みた。" },
  { id:"v011", term:"available", pos:"adj.", jp:"利用できる、手が空いている", ex:"Are you available this afternoon?", exJp:"今日の午後は空いていますか?" },
  { id:"v012", term:"aware", pos:"adj.", jp:"気づいている", ex:"I wasn't aware of the change.", exJp:"その変更に気づいていなかった。" },
  { id:"v013", term:"benefit", pos:"n./v.", jp:"利益、恩恵を受ける", ex:"Everyone benefits from good sleep.", exJp:"誰もが良い睡眠から恩恵を受ける。" },
  { id:"v014", term:"circumstance", pos:"n.", jp:"状況、事情", ex:"Under these circumstances, we should wait.", exJp:"この状況では、待つべきだ。" },
  { id:"v015", term:"complicated", pos:"adj.", jp:"複雑な", ex:"The process is more complicated than it looks.", exJp:"その手順は見た目より複雑だ。" },
  { id:"v016", term:"consequence", pos:"n.", jp:"結果、影響", ex:"He didn't think about the consequences.", exJp:"彼は結果を考えなかった。" },
  { id:"v017", term:"consider", pos:"v.", jp:"考慮する、みなす", ex:"Please consider my suggestion.", exJp:"私の提案を検討してください。" },
  { id:"v018", term:"consistent", pos:"adj.", jp:"一貫した、矛盾のない", ex:"Her work is always consistent.", exJp:"彼女の仕事は常に安定している。" },
  { id:"v019", term:"convince", pos:"v.", jp:"納得させる、説得する", ex:"He convinced me to try again.", exJp:"彼は私にもう一度挑戦するよう説得した。" },
  { id:"v020", term:"crucial", pos:"adj.", jp:"極めて重要な", ex:"Timing is crucial in this business.", exJp:"この業界ではタイミングが極めて重要だ。" },
  { id:"v021", term:"decline", pos:"v./n.", jp:"断る、減少する、減少", ex:"Sales declined sharply last year.", exJp:"昨年、売上が急激に減少した。" },
  { id:"v022", term:"dedicate", pos:"v.", jp:"捧げる、専念する", ex:"She dedicated her life to teaching.", exJp:"彼女は人生を教育に捧げた。" },
  { id:"v023", term:"demonstrate", pos:"v.", jp:"実演する、証明する", ex:"Let me demonstrate how it works.", exJp:"どう動くか実演させてください。" },
  { id:"v024", term:"determine", pos:"v.", jp:"決定する、突き止める", ex:"We need to determine the cause.", exJp:"原因を突き止める必要がある。" },
  { id:"v025", term:"distinguish", pos:"v.", jp:"見分ける、区別する", ex:"It's hard to distinguish the two.", exJp:"その2つを見分けるのは難しい。" },
  { id:"v026", term:"efficient", pos:"adj.", jp:"効率的な", ex:"This is a more efficient way to work.", exJp:"これはより効率的な働き方だ。" },
  { id:"v027", term:"eliminate", pos:"v.", jp:"取り除く、排除する", ex:"We tried to eliminate all the errors.", exJp:"すべての誤りを取り除こうとした。" },
  { id:"v028", term:"emphasize", pos:"v.", jp:"強調する", ex:"He emphasized the need for safety.", exJp:"彼は安全の必要性を強調した。" },
  { id:"v029", term:"encounter", pos:"v./n.", jp:"遭遇する、出会い", ex:"We encountered several problems.", exJp:"いくつかの問題に遭遇した。" },
  { id:"v030", term:"essential", pos:"adj.", jp:"必要不可欠な", ex:"Water is essential for life.", exJp:"水は生命に不可欠だ。" },
  { id:"v031", term:"establish", pos:"v.", jp:"設立する、確立する", ex:"The company was established in 1990.", exJp:"その会社は1990年に設立された。" },
  { id:"v032", term:"estimate", pos:"v./n.", jp:"見積もる、見積もり", ex:"Can you estimate the cost?", exJp:"費用を見積もれますか?" },
  { id:"v033", term:"evident", pos:"adj.", jp:"明白な", ex:"Her talent was evident from the start.", exJp:"彼女の才能は最初から明白だった。" },
  { id:"v034", term:"exceed", pos:"v.", jp:"超える、上回る", ex:"The results exceeded our expectations.", exJp:"結果は期待を上回った。" },
  { id:"v035", term:"expand", pos:"v.", jp:"拡大する、広げる", ex:"They plan to expand the business overseas.", exJp:"彼らは事業を海外に拡大する予定だ。" },
  { id:"v036", term:"figure out", pos:"phr.", jp:"理解する、解明する", ex:"I can't figure out how to solve it.", exJp:"どう解けばいいか分からない。" },
  { id:"v037", term:"frustrated", pos:"adj.", jp:"いらだった、失望した", ex:"I felt frustrated with the slow progress.", exJp:"進みの遅さにいらだった。" },
  { id:"v038", term:"genuine", pos:"adj.", jp:"本物の、誠実な", ex:"He showed genuine interest in the topic.", exJp:"彼はその話題に本物の関心を示した。" },
  { id:"v039", term:"guarantee", pos:"v./n.", jp:"保証する、保証", ex:"I can't guarantee the results.", exJp:"結果は保証できない。" },
  { id:"v040", term:"hesitate", pos:"v.", jp:"ためらう", ex:"Don't hesitate to ask questions.", exJp:"遠慮なく質問してください。" },
  { id:"v041", term:"identify", pos:"v.", jp:"特定する、識別する", ex:"Can you identify the man in the photo?", exJp:"写真の男性を特定できますか?" },
  { id:"v042", term:"impact", pos:"n./v.", jp:"影響、影響を与える", ex:"The news had a big impact on the market.", exJp:"そのニュースは市場に大きな影響を与えた。" },
  { id:"v043", term:"implement", pos:"v.", jp:"実行する、導入する", ex:"We will implement the new system soon.", exJp:"近く新しいシステムを導入する。" },
  { id:"v044", term:"indicate", pos:"v.", jp:"示す、指し示す", ex:"The data indicates a clear trend.", exJp:"そのデータは明確な傾向を示している。" },
  { id:"v045", term:"inevitable", pos:"adj.", jp:"避けられない", ex:"Change is inevitable.", exJp:"変化は避けられない。" },
  { id:"v046", term:"influence", pos:"n./v.", jp:"影響、影響を与える", ex:"His teacher had a strong influence on him.", exJp:"彼の先生は彼に強い影響を与えた。" },
  { id:"v047", term:"initial", pos:"adj.", jp:"最初の", ex:"My initial reaction was surprise.", exJp:"私の最初の反応は驚きだった。" },
  { id:"v048", term:"intend", pos:"v.", jp:"意図する、〜するつもり", ex:"I intend to finish it by Friday.", exJp:"金曜までに終えるつもりだ。" },
  { id:"v049", term:"involve", pos:"v.", jp:"含む、関与させる", ex:"The job involves a lot of travel.", exJp:"その仕事は多くの出張を伴う。" },
  { id:"v050", term:"maintain", pos:"v.", jp:"維持する、主張する", ex:"It's hard to maintain this pace.", exJp:"このペースを維持するのは難しい。" },
  { id:"v051", term:"manage to", pos:"phr.", jp:"どうにか〜する", ex:"We managed to catch the last train.", exJp:"どうにか最終電車に間に合った。" },
  { id:"v052", term:"moderate", pos:"adj.", jp:"適度な、穏やかな", ex:"He does moderate exercise every day.", exJp:"彼は毎日適度な運動をする。" },
  { id:"v053", term:"neglect", pos:"v.", jp:"怠る、無視する", ex:"Don't neglect your health.", exJp:"健康をおろそかにしてはいけない。" },
  { id:"v054", term:"obtain", pos:"v.", jp:"得る、手に入れる", ex:"You need a license to obtain the data.", exJp:"そのデータを得るには許可が要る。" },
  { id:"v055", term:"obvious", pos:"adj.", jp:"明らかな", ex:"The answer is obvious.", exJp:"答えは明らかだ。" },
  { id:"v056", term:"occur", pos:"v.", jp:"起こる、思い浮かぶ", ex:"The accident occurred at night.", exJp:"その事故は夜に起きた。" },
  { id:"v057", term:"opportunity", pos:"n.", jp:"機会", ex:"This is a great opportunity for you.", exJp:"これはあなたにとって絶好の機会だ。" },
  { id:"v058", term:"participate", pos:"v.", jp:"参加する", ex:"Everyone is welcome to participate.", exJp:"誰でも参加を歓迎します。" },
  { id:"v059", term:"particular", pos:"adj.", jp:"特定の、好みがうるさい", ex:"Is there a particular reason?", exJp:"何か特定の理由がありますか?" },
  { id:"v060", term:"perceive", pos:"v.", jp:"知覚する、捉える", ex:"How do customers perceive our brand?", exJp:"顧客は我々のブランドをどう捉えているか?" },
  { id:"v061", term:"persuade", pos:"v.", jp:"説得する", ex:"She persuaded him to stay.", exJp:"彼女は彼に残るよう説得した。" },
  { id:"v062", term:"potential", pos:"adj./n.", jp:"潜在的な、可能性", ex:"He has great potential as a leader.", exJp:"彼はリーダーとして大きな可能性がある。" },
  { id:"v063", term:"precise", pos:"adj.", jp:"正確な、精密な", ex:"I need the precise measurements.", exJp:"正確な寸法が必要だ。" },
  { id:"v064", term:"previous", pos:"adj.", jp:"以前の、前の", ex:"In my previous job, I traveled a lot.", exJp:"前の仕事ではよく出張した。" },
  { id:"v065", term:"priority", pos:"n.", jp:"優先事項", ex:"Safety is our top priority.", exJp:"安全が我々の最優先事項だ。" },
  { id:"v066", term:"proceed", pos:"v.", jp:"進む、続行する", ex:"Shall we proceed with the plan?", exJp:"その計画を進めましょうか?" },
  { id:"v067", term:"reasonable", pos:"adj.", jp:"妥当な、理にかなった", ex:"The price seems reasonable.", exJp:"その値段は妥当に思える。" },
  { id:"v068", term:"recognize", pos:"v.", jp:"認識する、それと分かる", ex:"I didn't recognize you at first.", exJp:"最初あなただと分からなかった。" },
  { id:"v069", term:"recommend", pos:"v.", jp:"勧める", ex:"I recommend trying the local food.", exJp:"地元の料理を試すのをお勧めします。" },
  { id:"v070", term:"regardless", pos:"adv.", jp:"〜に関わらず", ex:"We'll go regardless of the weather.", exJp:"天気に関わらず行きます。" },
  { id:"v071", term:"relevant", pos:"adj.", jp:"関連のある、適切な", ex:"That's not relevant to the topic.", exJp:"それは話題に関連がない。" },
  { id:"v072", term:"reliable", pos:"adj.", jp:"信頼できる", ex:"He is a reliable partner.", exJp:"彼は信頼できるパートナーだ。" },
  { id:"v073", term:"reluctant", pos:"adj.", jp:"気が進まない", ex:"She was reluctant to agree.", exJp:"彼女は同意するのに気が進まなかった。" },
  { id:"v074", term:"remarkable", pos:"adj.", jp:"注目すべき、見事な", ex:"He made remarkable progress.", exJp:"彼は目覚ましい進歩を遂げた。" },
  { id:"v075", term:"require", pos:"v.", jp:"必要とする、要求する", ex:"This task requires patience.", exJp:"この作業は忍耐を必要とする。" },
  { id:"v076", term:"resolve", pos:"v.", jp:"解決する、決意する", ex:"We need to resolve this issue quickly.", exJp:"この問題を早く解決する必要がある。" },
  { id:"v077", term:"respond", pos:"v.", jp:"応答する、反応する", ex:"He didn't respond to my email.", exJp:"彼は私のメールに返信しなかった。" },
  { id:"v078", term:"significant", pos:"adj.", jp:"重要な、著しい", ex:"There was a significant improvement.", exJp:"著しい改善があった。" },
  { id:"v079", term:"struggle", pos:"v./n.", jp:"苦労する、奮闘", ex:"I struggle to wake up early.", exJp:"早起きするのに苦労する。" },
  { id:"v080", term:"sufficient", pos:"adj.", jp:"十分な", ex:"We don't have sufficient time.", exJp:"十分な時間がない。" },
  { id:"v081", term:"suitable", pos:"adj.", jp:"適した、ふさわしい", ex:"This movie isn't suitable for children.", exJp:"この映画は子供に適さない。" },
  { id:"v082", term:"tend to", pos:"phr.", jp:"〜する傾向がある", ex:"I tend to forget names.", exJp:"私は名前を忘れがちだ。" },
  { id:"v083", term:"tolerate", pos:"v.", jp:"我慢する、許容する", ex:"I can't tolerate rude behavior.", exJp:"失礼な振る舞いは我慢できない。" },
  { id:"v084", term:"tremendous", pos:"adj.", jp:"途方もない、素晴らしい", ex:"They put in tremendous effort.", exJp:"彼らは途方もない努力を注いだ。" },
  { id:"v085", term:"undergo", pos:"v.", jp:"経験する、受ける", ex:"She had to undergo surgery.", exJp:"彼女は手術を受けなければならなかった。" },
  { id:"v086", term:"urge", pos:"v./n.", jp:"強く促す、衝動", ex:"I urge you to reconsider.", exJp:"再考することを強く勧めます。" },
  { id:"v087", term:"vary", pos:"v.", jp:"異なる、変化する", ex:"Prices vary from store to store.", exJp:"値段は店によって異なる。" },
  { id:"v088", term:"virtually", pos:"adv.", jp:"事実上、ほとんど", ex:"The room was virtually empty.", exJp:"部屋はほとんど空っぽだった。" },
  { id:"v089", term:"willing", pos:"adj.", jp:"進んで〜する、いとわない", ex:"Are you willing to help?", exJp:"手伝ってくれる気はありますか?" },
  { id:"v090", term:"worthwhile", pos:"adj.", jp:"価値のある", ex:"The trip was worthwhile.", exJp:"その旅行は価値があった。" },

  // --- 日常会話でよく使う動詞・句動詞 ---
  { id:"v091", term:"figure", pos:"v.", jp:"〜だと思う、判断する", ex:"I figured you'd be hungry.", exJp:"お腹すいてると思ったよ。" },
  { id:"v092", term:"bother", pos:"v.", jp:"悩ませる、わざわざ〜する", ex:"Don't bother, I'll do it myself.", exJp:"気にしないで、自分でやるから。" },
  { id:"v093", term:"mind", pos:"v.", jp:"気にする、嫌がる", ex:"I don't mind waiting.", exJp:"待つのは気にしないよ。" },
  { id:"v094", term:"afford", pos:"v.", jp:"〜する余裕がある", ex:"I can't afford a new car.", exJp:"新しい車を買う余裕はない。" },
  { id:"v095", term:"deserve", pos:"v.", jp:"〜に値する、〜して当然", ex:"You deserve a break.", exJp:"あなたは休んで当然だ。" },
  { id:"v096", term:"realize", pos:"v.", jp:"気づく、実感する", ex:"I didn't realize it was so late.", exJp:"こんなに遅いと気づかなかった。" },
  { id:"v097", term:"pretend", pos:"v.", jp:"〜のふりをする", ex:"He pretended not to hear me.", exJp:"彼は聞こえないふりをした。" },
  { id:"v098", term:"admit", pos:"v.", jp:"認める、白状する", ex:"I admit I was wrong.", exJp:"間違っていたと認めるよ。" },
  { id:"v099", term:"complain", pos:"v.", jp:"文句を言う、不平を言う", ex:"She always complains about work.", exJp:"彼女はいつも仕事の愚痴を言う。" },
  { id:"v100", term:"apologize", pos:"v.", jp:"謝る", ex:"I apologize for being late.", exJp:"遅れてすみません。" },
  { id:"v101", term:"suppose", pos:"v.", jp:"思う、たぶん〜だろう", ex:"I suppose you're right.", exJp:"たぶん君が正しいんだろうね。" },
  { id:"v102", term:"figure on", pos:"phr.", jp:"〜を見込む、当てにする", ex:"We figured on about ten guests.", exJp:"10人くらい来ると見込んでいた。" },
  { id:"v103", term:"come up with", pos:"phr.", jp:"思いつく、考え出す", ex:"She came up with a great idea.", exJp:"彼女は素晴らしい案を思いついた。" },
  { id:"v104", term:"put off", pos:"phr.", jp:"延期する、先延ばしにする", ex:"Don't put off your homework.", exJp:"宿題を後回しにしないで。" },
  { id:"v105", term:"give up", pos:"phr.", jp:"あきらめる、やめる", ex:"Don't give up so easily.", exJp:"そう簡単にあきらめないで。" },
  { id:"v106", term:"look forward to", pos:"phr.", jp:"〜を楽しみに待つ", ex:"I'm looking forward to the trip.", exJp:"旅行を楽しみにしている。" },
  { id:"v107", term:"get along with", pos:"phr.", jp:"〜と仲良くやる", ex:"I get along well with my coworkers.", exJp:"同僚とうまくやっている。" },
  { id:"v108", term:"run out of", pos:"phr.", jp:"〜を切らす、使い果たす", ex:"We ran out of milk.", exJp:"牛乳を切らしてしまった。" },
  { id:"v109", term:"deal with", pos:"phr.", jp:"対処する、扱う", ex:"I'll deal with it later.", exJp:"後で対処するよ。" },
  { id:"v110", term:"show up", pos:"phr.", jp:"現れる、来る", ex:"He didn't show up to the meeting.", exJp:"彼は会議に来なかった。" },
  { id:"v111", term:"work out", pos:"phr.", jp:"うまくいく、運動する", ex:"I hope everything works out.", exJp:"全部うまくいくといいな。" },
  { id:"v112", term:"look after", pos:"phr.", jp:"世話をする", ex:"Can you look after my dog?", exJp:"私の犬の面倒を見てくれる?" },
  { id:"v113", term:"turn out", pos:"phr.", jp:"結局〜になる、判明する", ex:"It turned out to be a great day.", exJp:"結局すばらしい一日になった。" },
  { id:"v114", term:"end up", pos:"phr.", jp:"最終的に〜になる", ex:"We ended up at a nice cafe.", exJp:"最終的にいいカフェにたどり着いた。" },
  { id:"v115", term:"get rid of", pos:"phr.", jp:"処分する、取り除く", ex:"I need to get rid of these old clothes.", exJp:"この古着を処分しないと。" },
  { id:"v116", term:"keep up with", pos:"phr.", jp:"遅れずについていく", ex:"It's hard to keep up with the news.", exJp:"ニュースについていくのは大変だ。" },
  { id:"v117", term:"make up", pos:"phr.", jp:"仲直りする、でっち上げる", ex:"They argued but made up quickly.", exJp:"彼らは口論したがすぐ仲直りした。" },
  { id:"v118", term:"break down", pos:"phr.", jp:"故障する、取り乱す", ex:"My car broke down on the way.", exJp:"途中で車が故障した。" },
  { id:"v119", term:"hang out", pos:"phr.", jp:"(気軽に)遊ぶ、過ごす", ex:"Let's hang out this weekend.", exJp:"今週末遊ぼうよ。" },
  { id:"v120", term:"check out", pos:"phr.", jp:"確認する、見てみる", ex:"You should check out this restaurant.", exJp:"このレストラン、見てみるといいよ。" },

  // --- 気持ち・様子を表す形容詞 ---
  { id:"v121", term:"annoyed", pos:"adj.", jp:"いらいらした", ex:"I was annoyed by the noise.", exJp:"その騒音にいらいらした。" },
  { id:"v122", term:"embarrassed", pos:"adj.", jp:"恥ずかしい、きまり悪い", ex:"I felt embarrassed about my mistake.", exJp:"自分のミスが恥ずかしかった。" },
  { id:"v123", term:"exhausted", pos:"adj.", jp:"へとへとに疲れた", ex:"I'm exhausted after work.", exJp:"仕事の後はへとへとだ。" },
  { id:"v124", term:"grateful", pos:"adj.", jp:"感謝している", ex:"I'm grateful for your support.", exJp:"支えてくれて感謝しています。" },
  { id:"v125", term:"nervous", pos:"adj.", jp:"緊張している、不安な", ex:"I'm nervous about the interview.", exJp:"面接が緊張する。" },
  { id:"v126", term:"confident", pos:"adj.", jp:"自信のある", ex:"She feels confident about the test.", exJp:"彼女は試験に自信がある。" },
  { id:"v127", term:"disappointed", pos:"adj.", jp:"がっかりした", ex:"I was disappointed with the result.", exJp:"結果にがっかりした。" },
  { id:"v128", term:"curious", pos:"adj.", jp:"知りたがりの、好奇心のある", ex:"I'm curious about how it works.", exJp:"どう動くのか知りたい。" },
  { id:"v129", term:"jealous", pos:"adj.", jp:"うらやましい、嫉妬した", ex:"I'm a little jealous of your trip.", exJp:"あなたの旅行が少しうらやましい。" },
  { id:"v130", term:"upset", pos:"adj.", jp:"動揺した、怒った", ex:"Don't be upset about it.", exJp:"そのことで動揺しないで。" },
  { id:"v131", term:"relieved", pos:"adj.", jp:"ほっとした", ex:"I was relieved to hear the news.", exJp:"その知らせを聞いてほっとした。" },
  { id:"v132", term:"overwhelmed", pos:"adj.", jp:"手一杯の、圧倒された", ex:"I feel overwhelmed with work.", exJp:"仕事で手一杯だ。" },
  { id:"v133", term:"awkward", pos:"adj.", jp:"気まずい、ぎこちない", ex:"There was an awkward silence.", exJp:"気まずい沈黙があった。" },
  { id:"v134", term:"decent", pos:"adj.", jp:"まともな、悪くない", ex:"It's a decent place to eat.", exJp:"食事するには悪くない店だ。" },
  { id:"v135", term:"gorgeous", pos:"adj.", jp:"とても美しい、豪華な", ex:"The view was gorgeous.", exJp:"その景色は見事だった。" },
  { id:"v136", term:"tough", pos:"adj.", jp:"大変な、丈夫な", ex:"It was a tough week.", exJp:"大変な一週間だった。" },
  { id:"v137", term:"tiny", pos:"adj.", jp:"とても小さい", ex:"They live in a tiny apartment.", exJp:"彼らはとても小さなアパートに住んでいる。" },
  { id:"v138", term:"weird", pos:"adj.", jp:"変な、奇妙な", ex:"That's a weird coincidence.", exJp:"それは変な偶然だね。" },
  { id:"v139", term:"scared", pos:"adj.", jp:"怖がっている", ex:"I'm scared of heights.", exJp:"高いところが怖い。" },
  { id:"v140", term:"proud", pos:"adj.", jp:"誇りに思う", ex:"I'm proud of you.", exJp:"あなたを誇りに思う。" },

  // --- 日常の名詞・その他 ---
  { id:"v141", term:"issue", pos:"n.", jp:"問題、課題", ex:"We have a small issue to solve.", exJp:"解決すべき小さな問題がある。" },
  { id:"v142", term:"favor", pos:"n.", jp:"頼み事、親切", ex:"Can I ask you a favor?", exJp:"お願いしてもいい?" },
  { id:"v143", term:"deadline", pos:"n.", jp:"締め切り", ex:"The deadline is next Friday.", exJp:"締め切りは来週の金曜だ。" },
  { id:"v144", term:"appointment", pos:"n.", jp:"予約、約束", ex:"I have a doctor's appointment.", exJp:"医者の予約がある。" },
  { id:"v145", term:"attitude", pos:"n.", jp:"態度、姿勢", ex:"I like his positive attitude.", exJp:"彼の前向きな態度が好きだ。" },
  { id:"v146", term:"budget", pos:"n.", jp:"予算", ex:"That's over my budget.", exJp:"それは予算オーバーだ。" },
  { id:"v147", term:"habit", pos:"n.", jp:"習慣、癖", ex:"Reading is a good habit.", exJp:"読書は良い習慣だ。" },
  { id:"v148", term:"mood", pos:"n.", jp:"気分、機嫌", ex:"I'm not in the mood today.", exJp:"今日はそんな気分じゃない。" },
  { id:"v149", term:"advantage", pos:"n.", jp:"利点、有利", ex:"Speaking English is a big advantage.", exJp:"英語が話せるのは大きな強みだ。" },
  { id:"v150", term:"impression", pos:"n.", jp:"印象", ex:"He made a good first impression.", exJp:"彼は良い第一印象を与えた。" },
  { id:"v151", term:"opportunity", pos:"n.", jp:"機会、チャンス", ex:"Don't miss this opportunity.", exJp:"この機会を逃さないで。" },
  { id:"v152", term:"situation", pos:"n.", jp:"状況", ex:"It's a difficult situation.", exJp:"難しい状況だ。" },
  { id:"v153", term:"response", pos:"n.", jp:"返答、反応", ex:"I'm still waiting for a response.", exJp:"まだ返事を待っている。" },
  { id:"v154", term:"schedule", pos:"n./v.", jp:"予定、予定を組む", ex:"My schedule is full this week.", exJp:"今週は予定が詰まっている。" },
  { id:"v155", term:"effort", pos:"n.", jp:"努力", ex:"It takes a lot of effort.", exJp:"多くの努力が必要だ。" },
  { id:"v156", term:"progress", pos:"n.", jp:"進歩、進展", ex:"You're making good progress.", exJp:"順調に進歩しているね。" },
  { id:"v157", term:"advice", pos:"n.", jp:"助言", ex:"Can I give you some advice?", exJp:"アドバイスしてもいい?" },
  { id:"v158", term:"reason", pos:"n.", jp:"理由", ex:"There's no reason to worry.", exJp:"心配する理由はない。" },
  { id:"v159", term:"chance", pos:"n.", jp:"可能性、機会", ex:"Is there any chance you're free?", exJp:"ひょっとして空いてる可能性はある?" },
  { id:"v160", term:"experience", pos:"n./v.", jp:"経験、経験する", ex:"It was a great experience.", exJp:"素晴らしい経験だった。" },

  // --- 副詞・つなぎ言葉(会話をなめらかに) ---
  { id:"v161", term:"actually", pos:"adv.", jp:"実は、実際には", ex:"Actually, I've never been there.", exJp:"実は、そこには行ったことがない。" },
  { id:"v162", term:"basically", pos:"adv.", jp:"基本的に、要するに", ex:"Basically, it's the same thing.", exJp:"要するに、同じことだよ。" },
  { id:"v163", term:"eventually", pos:"adv.", jp:"最終的に、いずれ", ex:"You'll get used to it eventually.", exJp:"いずれ慣れるよ。" },
  { id:"v164", term:"honestly", pos:"adv.", jp:"正直に言うと", ex:"Honestly, I don't know.", exJp:"正直、分からない。" },
  { id:"v165", term:"probably", pos:"adv.", jp:"たぶん、おそらく", ex:"I'll probably be late.", exJp:"たぶん遅れると思う。" },
  { id:"v166", term:"definitely", pos:"adv.", jp:"間違いなく、絶対に", ex:"I'll definitely be there.", exJp:"絶対に行くよ。" },
  { id:"v167", term:"barely", pos:"adv.", jp:"かろうじて、ほとんど〜ない", ex:"I could barely hear you.", exJp:"ほとんど聞こえなかった。" },
  { id:"v168", term:"hardly", pos:"adv.", jp:"ほとんど〜ない", ex:"I hardly ever eat out.", exJp:"外食はめったにしない。" },
  { id:"v169", term:"lately", pos:"adv.", jp:"最近", ex:"I've been busy lately.", exJp:"最近忙しい。" },
  { id:"v170", term:"instead", pos:"adv.", jp:"代わりに", ex:"Let's take the train instead.", exJp:"代わりに電車で行こう。" },
  { id:"v171", term:"anyway", pos:"adv.", jp:"とにかく、どのみち", ex:"Anyway, let's move on.", exJp:"とにかく、先に進もう。" },
  { id:"v172", term:"somehow", pos:"adv.", jp:"どうにかして、なぜか", ex:"We'll manage somehow.", exJp:"どうにかなるよ。" },
  { id:"v173", term:"otherwise", pos:"adv.", jp:"さもないと、その他は", ex:"Hurry, otherwise we'll be late.", exJp:"急いで、さもないと遅れる。" },
  { id:"v174", term:"meanwhile", pos:"adv.", jp:"その間に、一方", ex:"Meanwhile, I'll prepare dinner.", exJp:"その間に、私が夕食を作るよ。" },
  { id:"v175", term:"apparently", pos:"adv.", jp:"どうやら〜らしい", ex:"Apparently, they broke up.", exJp:"どうやら彼らは別れたらしい。" },

  // --- さらに実用動詞 ---
  { id:"v176", term:"remind", pos:"v.", jp:"思い出させる", ex:"Remind me to call her.", exJp:"彼女に電話するの、思い出させて。" },
  { id:"v177", term:"prefer", pos:"v.", jp:"〜の方を好む", ex:"I prefer tea to coffee.", exJp:"コーヒーより紅茶が好き。" },
  { id:"v178", term:"expect", pos:"v.", jp:"予期する、期待する", ex:"I didn't expect to see you here.", exJp:"ここで会うとは思わなかった。" },
  { id:"v179", term:"promise", pos:"v./n.", jp:"約束する、約束", ex:"I promise I'll be careful.", exJp:"気をつけると約束するよ。" },
  { id:"v180", term:"wonder", pos:"v.", jp:"〜かなと思う、不思議に思う", ex:"I wonder what happened.", exJp:"何があったんだろう。" },
  { id:"v181", term:"consider", pos:"v.", jp:"検討する", ex:"I'll consider it.", exJp:"検討してみるよ。" },
  { id:"v182", term:"prepare", pos:"v.", jp:"準備する", ex:"I need to prepare for the meeting.", exJp:"会議の準備をしないと。" },
  { id:"v183", term:"handle", pos:"v.", jp:"扱う、対処する", ex:"Can you handle this alone?", exJp:"一人で対処できる?" },
  { id:"v184", term:"replace", pos:"v.", jp:"取り替える、代わりになる", ex:"We need to replace the battery.", exJp:"電池を交換する必要がある。" },
  { id:"v185", term:"complete", pos:"v./adj.", jp:"完了する、完全な", ex:"Did you complete the form?", exJp:"用紙は書き終えた?" },
  { id:"v186", term:"improve", pos:"v.", jp:"改善する、上達する", ex:"My English is improving.", exJp:"英語が上達している。" },
  { id:"v187", term:"avoid", pos:"v.", jp:"避ける", ex:"Try to avoid junk food.", exJp:"ジャンクフードは避けよう。" },
  { id:"v188", term:"allow", pos:"v.", jp:"許す、可能にする", ex:"They don't allow pets here.", exJp:"ここはペット禁止だ。" },
  { id:"v189", term:"suggest", pos:"v.", jp:"提案する", ex:"I suggest we leave early.", exJp:"早めに出ることを提案するよ。" },
  { id:"v190", term:"mention", pos:"v.", jp:"言及する、口にする", ex:"She mentioned it yesterday.", exJp:"彼女は昨日それに触れていた。" },
  { id:"v191", term:"notice", pos:"v.", jp:"気づく", ex:"I noticed you changed your hair.", exJp:"髪型変えたのに気づいたよ。" },
  { id:"v192", term:"manage", pos:"v.", jp:"どうにかやる、管理する", ex:"How do you manage everything?", exJp:"どうやって全部こなしてるの?" },
  { id:"v193", term:"afford to", pos:"phr.", jp:"〜する余裕がある", ex:"We can't afford to lose.", exJp:"負ける余裕はない。" },
  { id:"v194", term:"rely on", pos:"phr.", jp:"頼る、当てにする", ex:"You can rely on me.", exJp:"私を頼っていいよ。" },
  { id:"v195", term:"focus on", pos:"phr.", jp:"〜に集中する", ex:"Let's focus on the main issue.", exJp:"主要な問題に集中しよう。" },
  { id:"v196", term:"insist", pos:"v.", jp:"強く主張する、言い張る", ex:"He insisted on paying.", exJp:"彼はどうしても払うと言い張った。" },
  { id:"v197", term:"appreciate", pos:"v.", jp:"ありがたく思う", ex:"I really appreciate it.", exJp:"本当に感謝します。" },
  { id:"v198", term:"blame", pos:"v.", jp:"責める、〜のせいにする", ex:"Don't blame yourself.", exJp:"自分を責めないで。" },
  { id:"v199", term:"quit", pos:"v.", jp:"やめる", ex:"He quit his job last month.", exJp:"彼は先月仕事を辞めた。" },
  { id:"v200", term:"relax", pos:"v.", jp:"くつろぐ、落ち着く", ex:"Just relax and enjoy it.", exJp:"リラックスして楽しんで。" },
];

// ---- 表現テンプレート (Expression / sentence frames) ----
// frame: 型 / jp: 意味 / note: 使い方メモ / examples: 差し替え例
const EXPRESSIONS = [
  { id:"e001", frame:"Should I ~?", jp:"〜すべき?/〜した方がいい?", note:"相手に助言を求める。~ は動詞の原形。",
    examples:[ {en:"Should I bring anything?", jp:"何か持って行くべき?"}, {en:"Should I call him now?", jp:"今、彼に電話すべき?"}, {en:"Should I wait here?", jp:"ここで待つべき?"} ] },
  { id:"e002", frame:"Do you mind if I ~?", jp:"〜してもいいですか?(丁寧)", note:"許可を丁寧に求める。答えは No が「どうぞ」。~ は動詞の原形。",
    examples:[ {en:"Do you mind if I sit here?", jp:"ここに座ってもいいですか?"}, {en:"Do you mind if I open the window?", jp:"窓を開けてもいいですか?"} ] },
  { id:"e003", frame:"Would you mind ~ing?", jp:"〜していただけますか?(丁寧な依頼)", note:"~ は動詞ing形。",
    examples:[ {en:"Would you mind helping me?", jp:"手伝っていただけますか?"}, {en:"Would you mind waiting a moment?", jp:"少し待っていただけますか?"} ] },
  { id:"e004", frame:"I was about to ~", jp:"ちょうど〜しようとしていた", note:"直前の動作。~ は動詞の原形。",
    examples:[ {en:"I was about to call you.", jp:"ちょうど電話しようとしていた。"}, {en:"I was about to leave.", jp:"ちょうど出ようとしていた。"} ] },
  { id:"e005", frame:"I'm supposed to ~", jp:"〜することになっている", note:"予定・義務・ルール。~ は動詞の原形。",
    examples:[ {en:"I'm supposed to meet her at six.", jp:"6時に彼女と会うことになっている。"}, {en:"You're not supposed to park here.", jp:"ここに駐車してはいけないことになっている。"} ] },
  { id:"e006", frame:"You might want to ~", jp:"〜した方がいいかも(やわらかい助言)", note:"押し付けない提案。~ は動詞の原形。",
    examples:[ {en:"You might want to check the schedule.", jp:"予定を確認した方がいいかも。"}, {en:"You might want to leave early.", jp:"早めに出た方がいいかも。"} ] },
  { id:"e007", frame:"Why don't we ~?", jp:"〜しませんか?(提案)", note:"一緒に何かをする提案。~ は動詞の原形。",
    examples:[ {en:"Why don't we take a break?", jp:"休憩しませんか?"}, {en:"Why don't we ask him?", jp:"彼に聞いてみませんか?"} ] },
  { id:"e008", frame:"How about ~ing?", jp:"〜するのはどう?", note:"提案。~ は名詞か動詞ing形。",
    examples:[ {en:"How about meeting at noon?", jp:"正午に会うのはどう?"}, {en:"How about Italian food?", jp:"イタリアンはどう?"} ] },
  { id:"e009", frame:"I'd rather ~", jp:"むしろ〜したい / 〜する方がいい", note:"控えめな好みの主張。~ は動詞の原形。than で比較も。",
    examples:[ {en:"I'd rather stay home tonight.", jp:"今夜はむしろ家にいたい。"}, {en:"I'd rather walk than take a taxi.", jp:"タクシーより歩きたい。"} ] },
  { id:"e010", frame:"I feel like ~ing", jp:"〜したい気分だ", note:"~ は動詞ing形。",
    examples:[ {en:"I feel like eating something sweet.", jp:"甘いものが食べたい気分だ。"}, {en:"I don't feel like working today.", jp:"今日は働く気分じゃない。"} ] },
  { id:"e011", frame:"It's worth ~ing", jp:"〜する価値がある", note:"~ は動詞ing形。",
    examples:[ {en:"It's worth trying at least once.", jp:"少なくとも一度は試す価値がある。"}, {en:"This place is worth visiting.", jp:"ここは訪れる価値がある。"} ] },
  { id:"e012", frame:"I can't help ~ing", jp:"〜せずにはいられない", note:"~ は動詞ing形。",
    examples:[ {en:"I can't help laughing.", jp:"笑わずにはいられない。"}, {en:"I can't help worrying about it.", jp:"それが心配で仕方ない。"} ] },
  { id:"e013", frame:"I'm thinking of ~ing", jp:"〜しようかと思っている", note:"~ は動詞ing形。",
    examples:[ {en:"I'm thinking of changing jobs.", jp:"転職しようかと思っている。"}, {en:"I'm thinking of going to Japan.", jp:"日本に行こうかと思っている。"} ] },
  { id:"e014", frame:"Make sure you ~", jp:"必ず〜してね", note:"念押し・指示。~ は動詞の原形。",
    examples:[ {en:"Make sure you lock the door.", jp:"必ずドアに鍵をかけてね。"}, {en:"Make sure you save your work.", jp:"必ず作業を保存してね。"} ] },
  { id:"e015", frame:"You'd better ~", jp:"〜した方がいい(強め・警告)", note:"やらないと困る含み。~ は動詞の原形。",
    examples:[ {en:"You'd better hurry.", jp:"急いだ方がいい。"}, {en:"You'd better not be late.", jp:"遅れない方がいい。"} ] },
  { id:"e016", frame:"Is it okay if I ~?", jp:"〜してもいい?(カジュアルな許可)", note:"~ は動詞の原形。",
    examples:[ {en:"Is it okay if I leave early?", jp:"早退してもいい?"}, {en:"Is it okay if I bring a friend?", jp:"友達を連れてきてもいい?"} ] },
  { id:"e017", frame:"Do you happen to know ~?", jp:"ひょっとして〜を知ってる?", note:"やわらかく尋ねる。~ は名詞/wh節。",
    examples:[ {en:"Do you happen to know his number?", jp:"ひょっとして彼の番号知ってる?"}, {en:"Do you happen to know where it is?", jp:"ひょっとしてそれがどこか知ってる?"} ] },
  { id:"e018", frame:"I was wondering if you could ~", jp:"〜していただけないかと思って(丁寧な依頼)", note:"~ は動詞の原形。",
    examples:[ {en:"I was wondering if you could help me.", jp:"手伝っていただけないかと思って。"}, {en:"I was wondering if you could send it today.", jp:"今日送っていただけないかと思って。"} ] },
  { id:"e019", frame:"There's no point in ~ing", jp:"〜しても意味がない", note:"~ は動詞ing形。",
    examples:[ {en:"There's no point in arguing.", jp:"言い争っても意味がない。"}, {en:"There's no point in waiting.", jp:"待っても意味がない。"} ] },
  { id:"e020", frame:"I'm used to ~ing", jp:"〜するのに慣れている", note:"~ は動詞ing形(または名詞)。",
    examples:[ {en:"I'm used to working late.", jp:"遅くまで働くのに慣れている。"}, {en:"I'm not used to the cold.", jp:"寒さに慣れていない。"} ] },
  { id:"e021", frame:"I ended up ~ing", jp:"結局〜することになった", note:"~ は動詞ing形。",
    examples:[ {en:"I ended up staying home.", jp:"結局家にいることになった。"}, {en:"We ended up taking a taxi.", jp:"結局タクシーに乗ることになった。"} ] },
  { id:"e022", frame:"I might as well ~", jp:"どうせなら〜しておこう", note:"他に良い選択がない時。~ は動詞の原形。",
    examples:[ {en:"I might as well finish it now.", jp:"どうせなら今終わらせておこう。"}, {en:"We might as well walk.", jp:"どうせなら歩こう。"} ] },
  { id:"e023", frame:"What if we ~?", jp:"〜したらどうなる?/〜してみたら?", note:"仮の提案・懸念。~ は動詞の原形。",
    examples:[ {en:"What if we start earlier?", jp:"もっと早く始めたらどう?"}, {en:"What if it rains?", jp:"もし雨が降ったらどうする?"} ] },
  { id:"e024", frame:"Let me know if you ~", jp:"〜なら知らせてね", note:"~ は動詞(現在形)。",
    examples:[ {en:"Let me know if you need help.", jp:"助けが必要なら知らせてね。"}, {en:"Let me know if you change your mind.", jp:"気が変わったら知らせてね。"} ] },
  { id:"e025", frame:"Would it be possible to ~?", jp:"〜することは可能でしょうか?(丁寧)", note:"~ は動詞の原形。",
    examples:[ {en:"Would it be possible to reschedule?", jp:"予定を変更することは可能でしょうか?"}, {en:"Would it be possible to get a refund?", jp:"返金は可能でしょうか?"} ] },
  { id:"e026", frame:"I'd appreciate it if you could ~", jp:"〜していただけると助かります(丁寧)", note:"~ は動詞の原形。",
    examples:[ {en:"I'd appreciate it if you could reply soon.", jp:"早めにお返事いただけると助かります。"}, {en:"I'd appreciate it if you could confirm.", jp:"ご確認いただけると助かります。"} ] },
  { id:"e027", frame:"It looks like ~", jp:"〜のようだ / 〜みたいだ", note:"~ は主語+動詞。",
    examples:[ {en:"It looks like it's going to rain.", jp:"雨が降りそうだ。"}, {en:"It looks like we're early.", jp:"私たち早すぎたみたいだ。"} ] },
  { id:"e028", frame:"I'm not sure if ~", jp:"〜かどうか分からない", note:"~ は主語+動詞。",
    examples:[ {en:"I'm not sure if this is right.", jp:"これが正しいか分からない。"}, {en:"I'm not sure if he's coming.", jp:"彼が来るか分からない。"} ] },
  { id:"e029", frame:"No wonder ~", jp:"道理で〜なわけだ", note:"~ は主語+動詞。",
    examples:[ {en:"No wonder you're tired.", jp:"道理で疲れているわけだ。"}, {en:"No wonder it's so busy today.", jp:"道理で今日は混んでいるわけだ。"} ] },
  { id:"e030", frame:"The last thing I want to do is ~", jp:"一番〜したくない", note:"強い拒否。~ は動詞の原形。",
    examples:[ {en:"The last thing I want to do is bother you.", jp:"一番あなたに迷惑をかけたくない。"}, {en:"The last thing I want to do is give up.", jp:"一番あきらめたくない。"} ] },

  // --- 依頼・許可・提案 ---
  { id:"e031", frame:"Can you ~ for me?", jp:"〜してもらえる?(カジュアルな依頼)", note:"~ は動詞の原形。",
    examples:[ {en:"Can you hold this for me?", jp:"これ持っててもらえる?"}, {en:"Can you check this for me?", jp:"これ確認してもらえる?"} ] },
  { id:"e032", frame:"Could you possibly ~?", jp:"できれば〜していただけますか?(丁寧)", note:"~ は動詞の原形。",
    examples:[ {en:"Could you possibly move your car?", jp:"できれば車を動かしていただけますか?"}, {en:"Could you possibly call me back?", jp:"できれば折り返しお電話いただけますか?"} ] },
  { id:"e033", frame:"Feel free to ~", jp:"遠慮なく〜してね", note:"~ は動詞の原形。",
    examples:[ {en:"Feel free to ask me anything.", jp:"何でも遠慮なく聞いてね。"}, {en:"Feel free to help yourself.", jp:"遠慮なくご自由にどうぞ。"} ] },
  { id:"e034", frame:"Let's ~ instead of ~ing", jp:"〜する代わりに〜しよう", note:"前は原形、後ろはing形。",
    examples:[ {en:"Let's walk instead of driving.", jp:"車の代わりに歩こう。"}, {en:"Let's cook instead of eating out.", jp:"外食の代わりに料理しよう。"} ] },
  { id:"e035", frame:"Shall we ~?", jp:"〜しましょうか?", note:"丁寧な誘い。~ は動詞の原形。",
    examples:[ {en:"Shall we get started?", jp:"始めましょうか?"}, {en:"Shall we go now?", jp:"もう行きましょうか?"} ] },

  // --- 意見・感想を言う ---
  { id:"e036", frame:"I think ~", jp:"〜だと思う", note:"最も基本の意見表現。~ は主語+動詞。",
    examples:[ {en:"I think it's a good idea.", jp:"いい考えだと思う。"}, {en:"I think we should wait.", jp:"待つべきだと思う。"} ] },
  { id:"e037", frame:"It seems like ~", jp:"〜のようだ、〜な気がする", note:"~ は主語+動詞。",
    examples:[ {en:"It seems like a nice place.", jp:"いい場所のようだ。"}, {en:"It seems like he's busy.", jp:"彼は忙しいようだ。"} ] },
  { id:"e038", frame:"If I were you, I'd ~", jp:"私があなたなら〜する(助言)", note:"仮定法。~ は動詞の原形。",
    examples:[ {en:"If I were you, I'd take the job.", jp:"私なら、その仕事を受けるよ。"}, {en:"If I were you, I'd apologize.", jp:"私なら、謝るね。"} ] },
  { id:"e039", frame:"The thing is, ~", jp:"実はね、問題はね〜", note:"事情を切り出す。~ は主語+動詞。",
    examples:[ {en:"The thing is, I already have plans.", jp:"実はもう予定があるんだ。"}, {en:"The thing is, we're short on time.", jp:"問題は、時間が足りないことだ。"} ] },
  { id:"e040", frame:"To be honest, ~", jp:"正直に言うと〜", note:"~ は主語+動詞。",
    examples:[ {en:"To be honest, I don't like it.", jp:"正直、好きじゃない。"}, {en:"To be honest, I forgot.", jp:"正直、忘れてた。"} ] },
  { id:"e041", frame:"That's why ~", jp:"だから〜なんだ", note:"~ は主語+動詞。",
    examples:[ {en:"That's why I was late.", jp:"だから遅れたんだ。"}, {en:"That's why she's upset.", jp:"だから彼女は怒ってるんだ。"} ] },
  { id:"e042", frame:"As far as I know, ~", jp:"私の知る限り〜", note:"~ は主語+動詞。",
    examples:[ {en:"As far as I know, it's free.", jp:"私の知る限り、無料だよ。"}, {en:"As far as I know, he's still here.", jp:"私の知る限り、彼はまだここにいるよ。"} ] },

  // --- 予定・意図・状態 ---
  { id:"e043", frame:"I'm going to ~", jp:"〜するつもり / 〜する予定", note:"決めている予定。~ は動詞の原形。",
    examples:[ {en:"I'm going to call her later.", jp:"後で彼女に電話するつもり。"}, {en:"I'm going to start tomorrow.", jp:"明日から始める予定。"} ] },
  { id:"e044", frame:"I'm about to ~", jp:"今から〜するところ", note:"直前。~ は動詞の原形。",
    examples:[ {en:"I'm about to leave.", jp:"今から出るところ。"}, {en:"I'm about to eat.", jp:"今から食べるところ。"} ] },
  { id:"e045", frame:"I've been ~ing", jp:"ずっと〜している(継続)", note:"~ は動詞ing形。",
    examples:[ {en:"I've been studying English.", jp:"ずっと英語を勉強している。"}, {en:"I've been waiting for an hour.", jp:"1時間ずっと待っている。"} ] },
  { id:"e046", frame:"I used to ~", jp:"昔はよく〜したものだ", note:"過去の習慣。~ は動詞の原形。",
    examples:[ {en:"I used to play soccer.", jp:"昔はよくサッカーをした。"}, {en:"I used to live in Tokyo.", jp:"昔は東京に住んでいた。"} ] },
  { id:"e047", frame:"I'm trying to ~", jp:"〜しようとしている", note:"~ は動詞の原形。",
    examples:[ {en:"I'm trying to lose weight.", jp:"痩せようとしている。"}, {en:"I'm trying to focus.", jp:"集中しようとしている。"} ] },
  { id:"e048", frame:"I have no idea ~", jp:"〜か全く分からない", note:"~ は wh節。",
    examples:[ {en:"I have no idea what to do.", jp:"何をすべきか全く分からない。"}, {en:"I have no idea where he is.", jp:"彼がどこにいるか全く分からない。"} ] },

  // --- 会話の反応・あいづち ---
  { id:"e049", frame:"That sounds ~", jp:"それは〜そうだね", note:"~ は形容詞(good, great, difficult…)。",
    examples:[ {en:"That sounds great!", jp:"それはいいね!"}, {en:"That sounds difficult.", jp:"それは大変そうだね。"} ] },
  { id:"e050", frame:"I can't believe ~", jp:"〜なんて信じられない", note:"~ は主語+動詞。",
    examples:[ {en:"I can't believe it's already noon.", jp:"もう昼だなんて信じられない。"}, {en:"I can't believe you did that.", jp:"あなたがそれをしたなんて信じられない。"} ] },
  { id:"e051", frame:"It doesn't matter ~", jp:"〜は関係ない、どうでもいい", note:"~ は wh節 または省略。",
    examples:[ {en:"It doesn't matter what they think.", jp:"彼らがどう思おうと関係ない。"}, {en:"It doesn't matter to me.", jp:"私はどっちでもいいよ。"} ] },
  { id:"e052", frame:"No matter how ~, ~", jp:"どんなに〜でも", note:"譲歩。how の後に形容詞/副詞。",
    examples:[ {en:"No matter how hard it is, I won't quit.", jp:"どんなに大変でも、辞めない。"}, {en:"No matter how busy I am, I'll come.", jp:"どんなに忙しくても、行くよ。"} ] },
  { id:"e053", frame:"That's exactly what ~", jp:"それはまさに〜だ", note:"~ は主語+動詞。",
    examples:[ {en:"That's exactly what I meant.", jp:"それがまさに私の言いたかったこと。"}, {en:"That's exactly what I needed.", jp:"それがまさに欲しかったもの。"} ] },

  // --- 問題・お願い・気遣い ---
  { id:"e054", frame:"Would you like me to ~?", jp:"私が〜しましょうか?(申し出)", note:"~ は動詞の原形。",
    examples:[ {en:"Would you like me to help?", jp:"手伝いましょうか?"}, {en:"Would you like me to explain?", jp:"説明しましょうか?"} ] },
  { id:"e055", frame:"Do you want me to ~?", jp:"〜してほしい?(カジュアルな申し出)", note:"~ は動詞の原形。",
    examples:[ {en:"Do you want me to wait?", jp:"待っててほしい?"}, {en:"Do you want me to come with you?", jp:"一緒に行こうか?"} ] },
  { id:"e056", frame:"Make sure to ~", jp:"忘れずに〜してね", note:"~ は動詞の原形。",
    examples:[ {en:"Make sure to bring your ID.", jp:"身分証を忘れずに持ってきてね。"}, {en:"Make sure to drink water.", jp:"忘れずに水を飲んでね。"} ] },
  { id:"e057", frame:"You don't have to ~", jp:"〜しなくてもいいよ", note:"~ は動詞の原形。",
    examples:[ {en:"You don't have to worry.", jp:"心配しなくていいよ。"}, {en:"You don't have to come if you're tired.", jp:"疲れてるなら来なくていいよ。"} ] },
  { id:"e058", frame:"How am I supposed to ~?", jp:"どうやって〜しろっていうの?", note:"困惑・不満。~ は動詞の原形。",
    examples:[ {en:"How am I supposed to know that?", jp:"そんなの、どうやって分かるの?"}, {en:"How am I supposed to finish this today?", jp:"これ今日中にどうやって終わらせろと?"} ] },
  { id:"e059", frame:"I'd love to, but ~", jp:"ぜひそうしたいけど〜(丁寧な断り)", note:"~ は理由の文。",
    examples:[ {en:"I'd love to, but I'm busy tonight.", jp:"ぜひ行きたいけど、今夜は忙しくて。"}, {en:"I'd love to, but I have to work.", jp:"そうしたいけど、仕事があって。"} ] },
  { id:"e060", frame:"It's up to you", jp:"あなた次第だよ / 任せるよ", note:"決定を相手に委ねる定型句。",
    examples:[ {en:"Where should we eat? — It's up to you.", jp:"どこで食べる? — 任せるよ。"}, {en:"It's totally up to you.", jp:"完全に君次第だよ。"} ] },
];
