// ============================================================
//  学習コンテンツ (私が生成 / 追加はこの配列に足すだけ)
//  レベル: 英検2級の上 〜 準1級中心
// ============================================================

// ---- 単語 (Vocabulary) ----
// term: 英単語 / pos: 品詞 / jp: 意味 / ex: 例文 / exJp: 例文訳
const VOCAB = [
  { id:"v001", term:"accomplish", pos:"v.", jp:"成し遂げる", ex:"She accomplished her goal in three years.", exJp:"彼女は3年で目標を成し遂げた。" },
  { id:"v002", term:"acknowledge", pos:"v.", jp:"認める、認識する", ex:"He acknowledged that he was wrong.", exJp:"彼は自分が間違っていたと認めた。" },
  { id:"v003", term:"adequate", pos:"adj.", jp:"十分な、適切な", ex:"The salary is adequate for my needs.", exJp:"その給料は私の必要には十分だ。" },
  { id:"v004", term:"anticipate", pos:"v.", jp:"予期する、見込む", ex:"We anticipate a rise in sales next month.", exJp:"来月は売上の増加を見込んでいる。" },
  { id:"v005", term:"apparent", pos:"adj.", jp:"明らかな、見かけ上の", ex:"It was apparent that she was tired.", exJp:"彼女が疲れているのは明らかだった。" },
  { id:"v006", term:"appreciate", pos:"v.", jp:"感謝する、正しく理解する", ex:"I really appreciate your help.", exJp:"あなたの助けに本当に感謝します。" },
  { id:"v007", term:"appropriate", pos:"adj.", jp:"適切な、ふさわしい", ex:"That's not appropriate for a formal meeting.", exJp:"それは正式な会議にはふさわしくない。" },
  { id:"v008", term:"assume", pos:"v.", jp:"想定する、思い込む", ex:"I assumed you already knew.", exJp:"あなたはもう知っていると思っていた。" },
  { id:"v009", term:"assure", pos:"v.", jp:"保証する、断言する", ex:"I assure you it will be ready on time.", exJp:"時間通りに準備できると保証します。" },
  { id:"v010", term:"attempt", pos:"v./n.", jp:"試みる、試み", ex:"He made an attempt to fix it himself.", exJp:"彼は自分で直そうと試みた。" },
  { id:"v011", term:"available", pos:"adj.", jp:"利用できる、手が空いている", ex:"Are you available this afternoon?", exJp:"今日の午後は空いていますか?" },
  { id:"v012", term:"aware", pos:"adj.", jp:"気づいている", ex:"I wasn't aware of the change.", exJp:"その変更に気づいていなかった。" },
  { id:"v013", term:"benefit", pos:"n./v.", jp:"利益、恩恵を受ける", ex:"Everyone benefits from good sleep.", exJp:"誰もが良い睡眠から恩恵を受ける。" },
  { id:"v014", term:"circumstance", pos:"n.", jp:"状況、事情", ex:"Under these circumstances, we should wait.", exJp:"この状況では、待つべきだ。" },
  { id:"v015", term:"complicated", pos:"adj.", jp:"複雑な", ex:"The process is more complicated than it looks.", exJp:"その手順は見た目より複雑だ。" },
  { id:"v016", term:"consequence", pos:"n.", jp:"結果、影響", ex:"He didn't think about the consequences.", exJp:"彼は結果を考えなかった。" },
  { id:"v017", term:"consider", pos:"v.", jp:"考慮する、みなす", ex:"Please consider my suggestion.", exJp:"私の提案を検討してください。" },
  { id:"v018", term:"consistent", pos:"adj.", jp:"一貫した、矛盾のない", ex:"Her work is always consistent.", exJp:"彼女の仕事は常に安定している。" },
  { id:"v019", term:"convince", pos:"v.", jp:"納得させる、説得する", ex:"He convinced me to try again.", exJp:"彼は私にもう一度挑戦するよう説得した。" },
  { id:"v020", term:"crucial", pos:"adj.", jp:"極めて重要な", ex:"Timing is crucial in this business.", exJp:"この業界ではタイミングが極めて重要だ。" },
  { id:"v021", term:"decline", pos:"v./n.", jp:"断る、減少する、減少", ex:"Sales declined sharply last year.", exJp:"昨年、売上が急激に減少した。" },
  { id:"v022", term:"dedicate", pos:"v.", jp:"捧げる、専念する", ex:"She dedicated her life to teaching.", exJp:"彼女は人生を教育に捧げた。" },
  { id:"v023", term:"demonstrate", pos:"v.", jp:"実演する、証明する", ex:"Let me demonstrate how it works.", exJp:"どう動くか実演させてください。" },
  { id:"v024", term:"determine", pos:"v.", jp:"決定する、突き止める", ex:"We need to determine the cause.", exJp:"原因を突き止める必要がある。" },
  { id:"v025", term:"distinguish", pos:"v.", jp:"見分ける、区別する", ex:"It's hard to distinguish the two.", exJp:"その2つを見分けるのは難しい。" },
  { id:"v026", term:"efficient", pos:"adj.", jp:"効率的な", ex:"This is a more efficient way to work.", exJp:"これはより効率的な働き方だ。" },
  { id:"v027", term:"eliminate", pos:"v.", jp:"取り除く、排除する", ex:"We tried to eliminate all the errors.", exJp:"すべての誤りを取り除こうとした。" },
  { id:"v028", term:"emphasize", pos:"v.", jp:"強調する", ex:"He emphasized the need for safety.", exJp:"彼は安全の必要性を強調した。" },
  { id:"v029", term:"encounter", pos:"v./n.", jp:"遭遇する、出会い", ex:"We encountered several problems.", exJp:"いくつかの問題に遭遇した。" },
  { id:"v030", term:"essential", pos:"adj.", jp:"必要不可欠な", ex:"Water is essential for life.", exJp:"水は生命に不可欠だ。" },
  { id:"v031", term:"establish", pos:"v.", jp:"設立する、確立する", ex:"The company was established in 1990.", exJp:"その会社は1990年に設立された。" },
  { id:"v032", term:"estimate", pos:"v./n.", jp:"見積もる、見積もり", ex:"Can you estimate the cost?", exJp:"費用を見積もれますか?" },
  { id:"v033", term:"evident", pos:"adj.", jp:"明白な", ex:"Her talent was evident from the start.", exJp:"彼女の才能は最初から明白だった。" },
  { id:"v034", term:"exceed", pos:"v.", jp:"超える、上回る", ex:"The results exceeded our expectations.", exJp:"結果は期待を上回った。" },
  { id:"v035", term:"expand", pos:"v.", jp:"拡大する、広げる", ex:"They plan to expand the business overseas.", exJp:"彼らは事業を海外に拡大する予定だ。" },
  { id:"v036", term:"figure out", pos:"phr.", jp:"理解する、解明する", ex:"I can't figure out how to solve it.", exJp:"どう解けばいいか分からない。" },
  { id:"v037", term:"frustrated", pos:"adj.", jp:"いらだった、失望した", ex:"I felt frustrated with the slow progress.", exJp:"進みの遅さにいらだった。" },
  { id:"v038", term:"genuine", pos:"adj.", jp:"本物の、誠実な", ex:"He showed genuine interest in the topic.", exJp:"彼はその話題に本物の関心を示した。" },
  { id:"v039", term:"guarantee", pos:"v./n.", jp:"保証する、保証", ex:"I can't guarantee the results.", exJp:"結果は保証できない。" },
  { id:"v040", term:"hesitate", pos:"v.", jp:"ためらう", ex:"Don't hesitate to ask questions.", exJp:"遠慮なく質問してください。" },
  { id:"v041", term:"identify", pos:"v.", jp:"特定する、識別する", ex:"Can you identify the man in the photo?", exJp:"写真の男性を特定できますか?" },
  { id:"v042", term:"impact", pos:"n./v.", jp:"影響、影響を与える", ex:"The news had a big impact on the market.", exJp:"そのニュースは市場に大きな影響を与えた。" },
  { id:"v043", term:"implement", pos:"v.", jp:"実行する、導入する", ex:"We will implement the new system soon.", exJp:"近く新しいシステムを導入する。" },
  { id:"v044", term:"indicate", pos:"v.", jp:"示す、指し示す", ex:"The data indicates a clear trend.", exJp:"そのデータは明確な傾向を示している。" },
  { id:"v045", term:"inevitable", pos:"adj.", jp:"避けられない", ex:"Change is inevitable.", exJp:"変化は避けられない。" },
  { id:"v046", term:"influence", pos:"n./v.", jp:"影響、影響を与える", ex:"His teacher had a strong influence on him.", exJp:"彼の先生は彼に強い影響を与えた。" },
  { id:"v047", term:"initial", pos:"adj.", jp:"最初の", ex:"My initial reaction was surprise.", exJp:"私の最初の反応は驚きだった。" },
  { id:"v048", term:"intend", pos:"v.", jp:"意図する、〜するつもり", ex:"I intend to finish it by Friday.", exJp:"金曜までに終えるつもりだ。" },
  { id:"v049", term:"involve", pos:"v.", jp:"含む、関与させる", ex:"The job involves a lot of travel.", exJp:"その仕事は多くの出張を伴う。" },
  { id:"v050", term:"maintain", pos:"v.", jp:"維持する、主張する", ex:"It's hard to maintain this pace.", exJp:"このペースを維持するのは難しい。" },
  { id:"v051", term:"manage to", pos:"phr.", jp:"どうにか〜する", ex:"We managed to catch the last train.", exJp:"どうにか最終電車に間に合った。" },
  { id:"v052", term:"moderate", pos:"adj.", jp:"適度な、穏やかな", ex:"He does moderate exercise every day.", exJp:"彼は毎日適度な運動をする。" },
  { id:"v053", term:"neglect", pos:"v.", jp:"怠る、無視する", ex:"Don't neglect your health.", exJp:"健康をおろそかにしてはいけない。" },
  { id:"v054", term:"obtain", pos:"v.", jp:"得る、手に入れる", ex:"You need a license to obtain the data.", exJp:"そのデータを得るには許可が要る。" },
  { id:"v055", term:"obvious", pos:"adj.", jp:"明らかな", ex:"The answer is obvious.", exJp:"答えは明らかだ。" },
  { id:"v056", term:"occur", pos:"v.", jp:"起こる、思い浮かぶ", ex:"The accident occurred at night.", exJp:"その事故は夜に起きた。" },
  { id:"v057", term:"opportunity", pos:"n.", jp:"機会", ex:"This is a great opportunity for you.", exJp:"これはあなたにとって絶好の機会だ。" },
  { id:"v058", term:"participate", pos:"v.", jp:"参加する", ex:"Everyone is welcome to participate.", exJp:"誰でも参加を歓迎します。" },
  { id:"v059", term:"particular", pos:"adj.", jp:"特定の、好みがうるさい", ex:"Is there a particular reason?", exJp:"何か特定の理由がありますか?" },
  { id:"v060", term:"perceive", pos:"v.", jp:"知覚する、捉える", ex:"How do customers perceive our brand?", exJp:"顧客は我々のブランドをどう捉えているか?" },
  { id:"v061", term:"persuade", pos:"v.", jp:"説得する", ex:"She persuaded him to stay.", exJp:"彼女は彼に残るよう説得した。" },
  { id:"v062", term:"potential", pos:"adj./n.", jp:"潜在的な、可能性", ex:"He has great potential as a leader.", exJp:"彼はリーダーとして大きな可能性がある。" },
  { id:"v063", term:"precise", pos:"adj.", jp:"正確な、精密な", ex:"I need the precise measurements.", exJp:"正確な寸法が必要だ。" },
  { id:"v064", term:"previous", pos:"adj.", jp:"以前の、前の", ex:"In my previous job, I traveled a lot.", exJp:"前の仕事ではよく出張した。" },
  { id:"v065", term:"priority", pos:"n.", jp:"優先事項", ex:"Safety is our top priority.", exJp:"安全が我々の最優先事項だ。" },
  { id:"v066", term:"proceed", pos:"v.", jp:"進む、続行する", ex:"Shall we proceed with the plan?", exJp:"その計画を進めましょうか?" },
  { id:"v067", term:"reasonable", pos:"adj.", jp:"妥当な、理にかなった", ex:"The price seems reasonable.", exJp:"その値段は妥当に思える。" },
  { id:"v068", term:"recognize", pos:"v.", jp:"認識する、それと分かる", ex:"I didn't recognize you at first.", exJp:"最初あなただと分からなかった。" },
  { id:"v069", term:"recommend", pos:"v.", jp:"勧める", ex:"I recommend trying the local food.", exJp:"地元の料理を試すのをお勧めします。" },
  { id:"v070", term:"regardless", pos:"adv.", jp:"〜に関わらず", ex:"We'll go regardless of the weather.", exJp:"天気に関わらず行きます。" },
  { id:"v071", term:"relevant", pos:"adj.", jp:"関連のある、適切な", ex:"That's not relevant to the topic.", exJp:"それは話題に関連がない。" },
  { id:"v072", term:"reliable", pos:"adj.", jp:"信頼できる", ex:"He is a reliable partner.", exJp:"彼は信頼できるパートナーだ。" },
  { id:"v073", term:"reluctant", pos:"adj.", jp:"気が進まない", ex:"She was reluctant to agree.", exJp:"彼女は同意するのに気が進まなかった。" },
  { id:"v074", term:"remarkable", pos:"adj.", jp:"注目すべき、見事な", ex:"He made remarkable progress.", exJp:"彼は目覚ましい進歩を遂げた。" },
  { id:"v075", term:"require", pos:"v.", jp:"必要とする、要求する", ex:"This task requires patience.", exJp:"この作業は忍耐を必要とする。" },
  { id:"v076", term:"resolve", pos:"v.", jp:"解決する、決意する", ex:"We need to resolve this issue quickly.", exJp:"この問題を早く解決する必要がある。" },
  { id:"v077", term:"respond", pos:"v.", jp:"応答する、反応する", ex:"He didn't respond to my email.", exJp:"彼は私のメールに返信しなかった。" },
  { id:"v078", term:"significant", pos:"adj.", jp:"重要な、著しい", ex:"There was a significant improvement.", exJp:"著しい改善があった。" },
  { id:"v079", term:"struggle", pos:"v./n.", jp:"苦労する、奮闘", ex:"I struggle to wake up early.", exJp:"早起きするのに苦労する。" },
  { id:"v080", term:"sufficient", pos:"adj.", jp:"十分な", ex:"We don't have sufficient time.", exJp:"十分な時間がない。" },
  { id:"v081", term:"suitable", pos:"adj.", jp:"適した、ふさわしい", ex:"This movie isn't suitable for children.", exJp:"この映画は子供に適さない。" },
  { id:"v082", term:"tend to", pos:"phr.", jp:"〜する傾向がある", ex:"I tend to forget names.", exJp:"私は名前を忘れがちだ。" },
  { id:"v083", term:"tolerate", pos:"v.", jp:"我慢する、許容する", ex:"I can't tolerate rude behavior.", exJp:"失礼な振る舞いは我慢できない。" },
  { id:"v084", term:"tremendous", pos:"adj.", jp:"途方もない、素晴らしい", ex:"They put in tremendous effort.", exJp:"彼らは途方もない努力を注いだ。" },
  { id:"v085", term:"undergo", pos:"v.", jp:"経験する、受ける", ex:"She had to undergo surgery.", exJp:"彼女は手術を受けなければならなかった。" },
  { id:"v086", term:"urge", pos:"v./n.", jp:"強く促す、衝動", ex:"I urge you to reconsider.", exJp:"再考することを強く勧めます。" },
  { id:"v087", term:"vary", pos:"v.", jp:"異なる、変化する", ex:"Prices vary from store to store.", exJp:"値段は店によって異なる。" },
  { id:"v088", term:"virtually", pos:"adv.", jp:"事実上、ほとんど", ex:"The room was virtually empty.", exJp:"部屋はほとんど空っぽだった。" },
  { id:"v089", term:"willing", pos:"adj.", jp:"進んで〜する、いとわない", ex:"Are you willing to help?", exJp:"手伝ってくれる気はありますか?" },
  { id:"v090", term:"worthwhile", pos:"adj.", jp:"価値のある", ex:"The trip was worthwhile.", exJp:"その旅行は価値があった。" },
];

// ---- 表現テンプレート (Expression / sentence frames) ----
// frame: 型 / jp: 意味 / note: 使い方メモ / examples: 差し替え例
const EXPRESSIONS = [
  { id:"e001", frame:"Should I ~?", jp:"〜すべき?/〜した方がいい?", note:"相手に助言を求める。~ は動詞の原形。",
    examples:[ {en:"Should I bring anything?", jp:"何か持って行くべき?"}, {en:"Should I call him now?", jp:"今、彼に電話すべき?"}, {en:"Should I wait here?", jp:"ここで待つべき?"} ] },
  { id:"e002", frame:"Do you mind if I ~?", jp:"〜してもいいですか?(丁寧)", note:"許可を丁寧に求める。答えは No が「どうぞ」。~ は動詞の原形。",
    examples:[ {en:"Do you mind if I sit here?", jp:"ここに座ってもいいですか?"}, {en:"Do you mind if I open the window?", jp:"窓を開けてもいいですか?"} ] },
  { id:"e003", frame:"Would you mind ~ing?", jp:"〜していただけますか?(丁寧な依頼)", note:"~ は動詞ing形。",
    examples:[ {en:"Would you mind helping me?", jp:"手伝っていただけますか?"}, {en:"Would you mind waiting a moment?", jp:"少し待っていただけますか?"} ] },
  { id:"e004", frame:"I was about to ~", jp:"ちょうど〜しようとしていた", note:"直前の動作。~ は動詞の原形。",
    examples:[ {en:"I was about to call you.", jp:"ちょうど電話しようとしていた。"}, {en:"I was about to leave.", jp:"ちょうど出ようとしていた。"} ] },
  { id:"e005", frame:"I'm supposed to ~", jp:"〜することになっている", note:"予定・義務・ルール。~ は動詞の原形。",
    examples:[ {en:"I'm supposed to meet her at six.", jp:"6時に彼女と会うことになっている。"}, {en:"You're not supposed to park here.", jp:"ここに駐車してはいけないことになっている。"} ] },
  { id:"e006", frame:"You might want to ~", jp:"〜した方がいいかも(やわらかい助言)", note:"押し付けない提案。~ は動詞の原形。",
    examples:[ {en:"You might want to check the schedule.", jp:"予定を確認した方がいいかも。"}, {en:"You might want to leave early.", jp:"早めに出た方がいいかも。"} ] },
  { id:"e007", frame:"Why don't we ~?", jp:"〜しませんか?(提案)", note:"一緒に何かをする提案。~ は動詞の原形。",
    examples:[ {en:"Why don't we take a break?", jp:"休憩しませんか?"}, {en:"Why don't we ask him?", jp:"彼に聞いてみませんか?"} ] },
  { id:"e008", frame:"How about ~ing?", jp:"〜するのはどう?", note:"提案。~ は名詞か動詞ing形。",
    examples:[ {en:"How about meeting at noon?", jp:"正午に会うのはどう?"}, {en:"How about Italian food?", jp:"イタリアンはどう?"} ] },
  { id:"e009", frame:"I'd rather ~", jp:"むしろ〜したい / 〜する方がいい", note:"控えめな好みの主張。~ は動詞の原形。than で比較も。",
    examples:[ {en:"I'd rather stay home tonight.", jp:"今夜はむしろ家にいたい。"}, {en:"I'd rather walk than take a taxi.", jp:"タクシーより歩きたい。"} ] },
  { id:"e010", frame:"I feel like ~ing", jp:"〜したい気分だ", note:"~ は動詞ing形。",
    examples:[ {en:"I feel like eating something sweet.", jp:"甘いものが食べたい気分だ。"}, {en:"I don't feel like working today.", jp:"今日は働く気分じゃない。"} ] },
  { id:"e011", frame:"It's worth ~ing", jp:"〜する価値がある", note:"~ は動詞ing形。",
    examples:[ {en:"It's worth trying at least once.", jp:"少なくとも一度は試す価値がある。"}, {en:"This place is worth visiting.", jp:"ここは訪れる価値がある。"} ] },
  { id:"e012", frame:"I can't help ~ing", jp:"〜せずにはいられない", note:"~ は動詞ing形。",
    examples:[ {en:"I can't help laughing.", jp:"笑わずにはいられない。"}, {en:"I can't help worrying about it.", jp:"それが心配で仕方ない。"} ] },
  { id:"e013", frame:"I'm thinking of ~ing", jp:"〜しようかと思っている", note:"~ は動詞ing形。",
    examples:[ {en:"I'm thinking of changing jobs.", jp:"転職しようかと思っている。"}, {en:"I'm thinking of going to Japan.", jp:"日本に行こうかと思っている。"} ] },
  { id:"e014", frame:"Make sure you ~", jp:"必ず〜してね", note:"念押し・指示。~ は動詞の原形。",
    examples:[ {en:"Make sure you lock the door.", jp:"必ずドアに鍵をかけてね。"}, {en:"Make sure you save your work.", jp:"必ず作業を保存してね。"} ] },
  { id:"e015", frame:"You'd better ~", jp:"〜した方がいい(強め・警告)", note:"やらないと困る含み。~ は動詞の原形。",
    examples:[ {en:"You'd better hurry.", jp:"急いだ方がいい。"}, {en:"You'd better not be late.", jp:"遅れない方がいい。"} ] },
  { id:"e016", frame:"Is it okay if I ~?", jp:"〜してもいい?(カジュアルな許可)", note:"~ は動詞の原形。",
    examples:[ {en:"Is it okay if I leave early?", jp:"早退してもいい?"}, {en:"Is it okay if I bring a friend?", jp:"友達を連れてきてもいい?"} ] },
  { id:"e017", frame:"Do you happen to know ~?", jp:"ひょっとして〜を知ってる?", note:"やわらかく尋ねる。~ は名詞/wh節。",
    examples:[ {en:"Do you happen to know his number?", jp:"ひょっとして彼の番号知ってる?"}, {en:"Do you happen to know where it is?", jp:"ひょっとしてそれがどこか知ってる?"} ] },
  { id:"e018", frame:"I was wondering if you could ~", jp:"〜していただけないかと思って(丁寧な依頼)", note:"~ は動詞の原形。",
    examples:[ {en:"I was wondering if you could help me.", jp:"手伝っていただけないかと思って。"}, {en:"I was wondering if you could send it today.", jp:"今日送っていただけないかと思って。"} ] },
  { id:"e019", frame:"There's no point in ~ing", jp:"〜しても意味がない", note:"~ は動詞ing形。",
    examples:[ {en:"There's no point in arguing.", jp:"言い争っても意味がない。"}, {en:"There's no point in waiting.", jp:"待っても意味がない。"} ] },
  { id:"e020", frame:"I'm used to ~ing", jp:"〜するのに慣れている", note:"~ は動詞ing形(または名詞)。",
    examples:[ {en:"I'm used to working late.", jp:"遅くまで働くのに慣れている。"}, {en:"I'm not used to the cold.", jp:"寒さに慣れていない。"} ] },
  { id:"e021", frame:"I ended up ~ing", jp:"結局〜することになった", note:"~ は動詞ing形。",
    examples:[ {en:"I ended up staying home.", jp:"結局家にいることになった。"}, {en:"We ended up taking a taxi.", jp:"結局タクシーに乗ることになった。"} ] },
  { id:"e022", frame:"I might as well ~", jp:"どうせなら〜しておこう", note:"他に良い選択がない時。~ は動詞の原形。",
    examples:[ {en:"I might as well finish it now.", jp:"どうせなら今終わらせておこう。"}, {en:"We might as well walk.", jp:"どうせなら歩こう。"} ] },
  { id:"e023", frame:"What if we ~?", jp:"〜したらどうなる?/〜してみたら?", note:"仮の提案・懸念。~ は動詞の原形。",
    examples:[ {en:"What if we start earlier?", jp:"もっと早く始めたらどう?"}, {en:"What if it rains?", jp:"もし雨が降ったらどうする?"} ] },
  { id:"e024", frame:"Let me know if you ~", jp:"〜なら知らせてね", note:"~ は動詞(現在形)。",
    examples:[ {en:"Let me know if you need help.", jp:"助けが必要なら知らせてね。"}, {en:"Let me know if you change your mind.", jp:"気が変わったら知らせてね。"} ] },
  { id:"e025", frame:"Would it be possible to ~?", jp:"〜することは可能でしょうか?(丁寧)", note:"~ は動詞の原形。",
    examples:[ {en:"Would it be possible to reschedule?", jp:"予定を変更することは可能でしょうか?"}, {en:"Would it be possible to get a refund?", jp:"返金は可能でしょうか?"} ] },
  { id:"e026", frame:"I'd appreciate it if you could ~", jp:"〜していただけると助かります(丁寧)", note:"~ は動詞の原形。",
    examples:[ {en:"I'd appreciate it if you could reply soon.", jp:"早めにお返事いただけると助かります。"}, {en:"I'd appreciate it if you could confirm.", jp:"ご確認いただけると助かります。"} ] },
  { id:"e027", frame:"It looks like ~", jp:"〜のようだ / 〜みたいだ", note:"~ は主語+動詞。",
    examples:[ {en:"It looks like it's going to rain.", jp:"雨が降りそうだ。"}, {en:"It looks like we're early.", jp:"私たち早すぎたみたいだ。"} ] },
  { id:"e028", frame:"I'm not sure if ~", jp:"〜かどうか分からない", note:"~ は主語+動詞。",
    examples:[ {en:"I'm not sure if this is right.", jp:"これが正しいか分からない。"}, {en:"I'm not sure if he's coming.", jp:"彼が来るか分からない。"} ] },
  { id:"e029", frame:"No wonder ~", jp:"道理で〜なわけだ", note:"~ は主語+動詞。",
    examples:[ {en:"No wonder you're tired.", jp:"道理で疲れているわけだ。"}, {en:"No wonder it's so busy today.", jp:"道理で今日は混んでいるわけだ。"} ] },
  { id:"e030", frame:"The last thing I want to do is ~", jp:"一番〜したくない", note:"強い拒否。~ は動詞の原形。",
    examples:[ {en:"The last thing I want to do is bother you.", jp:"一番あなたに迷惑をかけたくない。"}, {en:"The last thing I want to do is give up.", jp:"一番あきらめたくない。"} ] },
];
