// ============================================================
//  各単語の「2つ目の例文」 (id で VOCAB に紐づけ)
// ============================================================
const EX2 = {
  v001:{en:"We finally accomplished what we set out to do.", jp:"私たちはついにやろうとしたことを成し遂げた。"},
  v002:{en:"The company acknowledged the mistake publicly.", jp:"その会社はミスを公に認めた。"},
  v003:{en:"Make sure you get adequate sleep before the exam.", jp:"試験前は十分な睡眠を取ってね。"},
  v004:{en:"I didn't anticipate such a strong reaction.", jp:"こんなに強い反応は予期していなかった。"},
  v005:{en:"For no apparent reason, the machine stopped.", jp:"はっきりした理由もなく、機械が止まった。"},
  v006:{en:"I'd appreciate a quick reply.", jp:"早めのお返事をいただけると助かります。"},
  v007:{en:"Please wear appropriate clothes for the event.", jp:"イベントにふさわしい服装で来てください。"},
  v008:{en:"Don't assume the worst.", jp:"最悪の事態を勝手に決めつけないで。"},
  v009:{en:"Let me assure you, everything is fine.", jp:"断言しますが、すべて大丈夫です。"},
  v010:{en:"This is my first attempt at cooking curry.", jp:"カレー作りはこれが初挑戦だ。"},
  v011:{en:"The report will be available tomorrow.", jp:"報告書は明日には手に入ります。"},
  v012:{en:"Are you aware of the risks?", jp:"リスクを分かっていますか?"},
  v013:{en:"There are many benefits to learning a language.", jp:"言語学習には多くの利点がある。"},
  v014:{en:"I can't leave under any circumstances.", jp:"どんな事情があっても離れられない。"},
  v015:{en:"Don't make things more complicated than they are.", jp:"物事を必要以上に複雑にしないで。"},
  v016:{en:"Every action has a consequence.", jp:"どんな行動にも結果が伴う。"},
  v017:{en:"Have you considered moving abroad?", jp:"海外移住を考えたことはある?"},
  v018:{en:"Try to be consistent with your practice.", jp:"練習は継続してやろう。"},
  v019:{en:"I couldn't convince them to change their minds.", jp:"彼らの考えを変えさせられなかった。"},
  v020:{en:"Getting enough rest is crucial.", jp:"十分な休養を取ることが極めて重要だ。"},
  v021:{en:"He politely declined the invitation.", jp:"彼は丁寧に招待を断った。"},
  v022:{en:"They dedicated the building to the founder.", jp:"彼らはその建物を創設者に捧げた。"},
  v023:{en:"The study demonstrates a clear link.", jp:"その研究は明確な関連性を示している。"},
  v024:{en:"The referee will determine the winner.", jp:"審判が勝者を決める。"},
  v025:{en:"Babies learn to distinguish voices early.", jp:"赤ちゃんは早くから声を聞き分ける。"},
  v026:{en:"We need a more efficient system.", jp:"もっと効率的なシステムが必要だ。"},
  v027:{en:"This step eliminates the risk of error.", jp:"この手順でミスの危険がなくなる。"},
  v028:{en:"I want to emphasize one point.", jp:"1点だけ強調しておきたい。"},
  v029:{en:"I encountered an old friend on the train.", jp:"電車で旧友に偶然会った。"},
  v030:{en:"Trust is essential in any team.", jp:"どんなチームでも信頼は不可欠だ。"},
  v031:{en:"They established a new branch in Osaka.", jp:"彼らは大阪に新支店を設立した。"},
  v032:{en:"It's hard to estimate how long it'll take.", jp:"どれくらいかかるか見積もるのは難しい。"},
  v033:{en:"It's evident that he's not interested.", jp:"彼が興味ないのは明白だ。"},
  v034:{en:"Demand exceeded supply this year.", jp:"今年は需要が供給を上回った。"},
  v035:{en:"We need to expand our vocabulary.", jp:"語彙を増やす必要がある。"},
  v036:{en:"I finally figured out the problem.", jp:"やっと問題が分かった。"},
  v037:{en:"Don't get frustrated if it takes time.", jp:"時間がかかってもいらいらしないで。"},
  v038:{en:"That's a genuine leather bag.", jp:"それは本革のバッグだ。"},
  v039:{en:"This product comes with a one-year guarantee.", jp:"この製品には1年保証が付く。"},
  v040:{en:"She hesitated before answering.", jp:"彼女は答える前にためらった。"},
  v041:{en:"We need to identify the root cause.", jp:"根本原因を特定する必要がある。"},
  v042:{en:"The decision had a lasting impact.", jp:"その決定は長く影響を残した。"},
  v043:{en:"It took months to implement the changes.", jp:"変更の実行に数ヶ月かかった。"},
  v044:{en:"All signs indicate success.", jp:"あらゆる兆候が成功を示している。"},
  v045:{en:"A delay now seems inevitable.", jp:"今や遅れは避けられないようだ。"},
  v046:{en:"Social media influences our choices.", jp:"SNSは私たちの選択に影響する。"},
  v047:{en:"The initial cost was higher than expected.", jp:"初期費用は予想より高かった。"},
  v048:{en:"What do you intend to do about it?", jp:"それについてどうするつもり?"},
  v049:{en:"This decision involves everyone.", jp:"この決定は全員に関わる。"},
  v050:{en:"They struggled to maintain their lead.", jp:"彼らはリードを保つのに苦労した。"},
  v051:{en:"Somehow I managed to finish on time.", jp:"どうにか時間内に終えられた。"},
  v052:{en:"Keep the volume at a moderate level.", jp:"音量は適度に保ってね。"},
  v053:{en:"He neglected to mention the cost.", jp:"彼は費用について言い忘れた。"},
  v054:{en:"How did you obtain this information?", jp:"どうやってこの情報を得たの?"},
  v055:{en:"For obvious reasons, I can't say more.", jp:"明らかな理由で、これ以上は言えない。"},
  v056:{en:"It never occurred to me to ask.", jp:"聞くなんて思いつきもしなかった。"},
  v057:{en:"Every problem is an opportunity to learn.", jp:"どんな問題も学ぶ機会だ。"},
  v058:{en:"About fifty people participated.", jp:"約50人が参加した。"},
  v059:{en:"She's very particular about coffee.", jp:"彼女はコーヒーにうるさい。"},
  v060:{en:"People perceive risk differently.", jp:"人はリスクの捉え方が違う。"},
  v061:{en:"It's hard to persuade a stubborn person.", jp:"頑固な人を説得するのは難しい。"},
  v062:{en:"The plan has huge potential.", jp:"その計画には大きな可能性がある。"},
  v063:{en:"Be precise about the time and place.", jp:"時間と場所は正確にね。"},
  v064:{en:"We met on a previous occasion.", jp:"以前にも会ったことがある。"},
  v065:{en:"Let's set our priorities first.", jp:"まず優先順位を決めよう。"},
  v066:{en:"You may proceed to the next step.", jp:"次の段階に進んでいいですよ。"},
  v067:{en:"Be reasonable about your expectations.", jp:"期待は現実的にね。"},
  v068:{en:"I recognized her voice immediately.", jp:"彼女の声だとすぐ分かった。"},
  v069:{en:"Can you recommend a good dentist?", jp:"いい歯医者を勧めてもらえる?"},
  v070:{en:"Everyone is welcome, regardless of age.", jp:"年齢に関わらず誰でも歓迎。"},
  v071:{en:"Please keep your comments relevant.", jp:"発言は本題に沿ったものにしてください。"},
  v072:{en:"We need a reliable internet connection.", jp:"信頼できるネット接続が必要だ。"},
  v073:{en:"He was reluctant to talk about it.", jp:"彼はそれについて話したがらなかった。"},
  v074:{en:"The view was truly remarkable.", jp:"その景色は本当に見事だった。"},
  v075:{en:"This position requires fluent English.", jp:"この職には流暢な英語が必要だ。"},
  v076:{en:"Let's resolve our differences calmly.", jp:"意見の違いは冷静に解決しよう。"},
  v077:{en:"How did they respond to your idea?", jp:"あなたの案に彼らはどう反応した?"},
  v078:{en:"There's a significant difference between them.", jp:"両者には大きな違いがある。"},
  v079:{en:"Many families struggle financially.", jp:"多くの家庭が金銭的に苦労している。"},
  v080:{en:"Is one hour sufficient?", jp:"1時間で十分?"},
  v081:{en:"Find a time suitable for everyone.", jp:"全員に都合のいい時間を見つけて。"},
  v082:{en:"Prices tend to rise in summer.", jp:"夏は値段が上がりがちだ。"},
  v083:{en:"I won't tolerate any excuses.", jp:"言い訳は一切許さない。"},
  v084:{en:"There was a tremendous amount of noise.", jp:"ものすごい騒音だった。"},
  v085:{en:"The city is undergoing big changes.", jp:"その街は大きな変化を経験している。"},
  v086:{en:"I feel a sudden urge to travel.", jp:"急に旅に出たい衝動を感じる。"},
  v087:{en:"Results may vary depending on the user.", jp:"結果は使う人によって異なる場合がある。"},
  v088:{en:"They are virtually the same product.", jp:"それらは事実上同じ製品だ。"},
  v089:{en:"Are you willing to compromise?", jp:"妥協する気はある?"},
  v090:{en:"It's worthwhile to double-check.", jp:"再確認する価値はある。"},

  v091:{en:"I figured it was too expensive.", jp:"高すぎると思ったんだ。"},
  v092:{en:"Sorry to bother you, but do you have a minute?", jp:"お邪魔してごめん、少しいい?"},
  v093:{en:"Would you mind closing the door?", jp:"ドアを閉めてもらえる?"},
  v094:{en:"We can't afford to waste time.", jp:"時間を無駄にする余裕はない。"},
  v095:{en:"You deserve better than this.", jp:"あなたはこんな扱いを受けるべきじゃない。"},
  v096:{en:"I just realized I forgot my keys.", jp:"鍵を忘れたと今気づいた。"},
  v097:{en:"Stop pretending everything is fine.", jp:"何もかも大丈夫なふりはやめて。"},
  v098:{en:"I have to admit, it was fun.", jp:"認めるよ、楽しかった。"},
  v099:{en:"There's no use complaining now.", jp:"今さら文句を言っても無駄だ。"},
  v100:{en:"He apologized for the misunderstanding.", jp:"彼は誤解について謝った。"},
  v101:{en:"I suppose we could try.", jp:"やってみてもいいかもね。"},
  v102:{en:"Don't figure on getting a refund.", jp:"返金は当てにしない方がいい。"},
  v103:{en:"Can you come up with a better plan?", jp:"もっといい案を思いつける?"},
  v104:{en:"Let's not put this off any longer.", jp:"これ以上先延ばしにするのはやめよう。"},
  v105:{en:"I almost gave up, but I kept going.", jp:"あきらめかけたけど、続けた。"},
  v106:{en:"I look forward to hearing from you.", jp:"ご連絡をお待ちしています。"},
  v107:{en:"Do you get along with your neighbors?", jp:"近所の人とはうまくやってる?"},
  v108:{en:"We're running out of time.", jp:"時間がなくなってきた。"},
  v109:{en:"She knows how to deal with pressure.", jp:"彼女はプレッシャーへの対処法を知っている。"},
  v110:{en:"Only half the team showed up.", jp:"チームの半分しか来なかった。"},
  v111:{en:"Don't worry, it'll all work out.", jp:"大丈夫、全部うまくいくよ。"},
  v112:{en:"Who looks after the kids?", jp:"子どもの面倒は誰が見るの?"},
  v113:{en:"It turned out I was wrong.", jp:"結局、私が間違っていた。"},
  v114:{en:"We might end up staying longer.", jp:"結局もっと長く滞在するかも。"},
  v115:{en:"I want to get rid of this old sofa.", jp:"この古いソファを処分したい。"},
  v116:{en:"I can't keep up with him.", jp:"彼のペースについていけない。"},
  v117:{en:"Let's make up and move on.", jp:"仲直りして前に進もう。"},
  v118:{en:"Talks broke down at the last minute.", jp:"交渉は土壇場で決裂した。"},
  v119:{en:"We used to hang out every weekend.", jp:"昔は毎週末一緒に遊んでいた。"},
  v120:{en:"Check out what I found!", jp:"見て、こんなの見つけた!"},

  v121:{en:"I get annoyed when people are late.", jp:"人が遅れるとイライラする。"},
  v122:{en:"He was embarrassed to ask for help.", jp:"彼は助けを求めるのが恥ずかしかった。"},
  v123:{en:"The kids are exhausted after the trip.", jp:"子どもたちは旅行の後へとへとだ。"},
  v124:{en:"I'm so grateful to have you.", jp:"あなたがいてくれて本当に感謝している。"},
  v125:{en:"Don't be nervous, you'll do great.", jp:"緊張しないで、うまくいくよ。"},
  v126:{en:"Stay confident even when it's hard.", jp:"大変な時も自信を持って。"},
  v127:{en:"I was disappointed that he didn't come.", jp:"彼が来なくてがっかりした。"},
  v128:{en:"Kids are naturally curious.", jp:"子どもは生まれつき好奇心が強い。"},
  v129:{en:"Don't be jealous of others' success.", jp:"他人の成功を妬まないで。"},
  v130:{en:"She got upset over a small thing.", jp:"彼女は些細なことで怒った。"},
  v131:{en:"I'm relieved it's finally over.", jp:"やっと終わってほっとした。"},
  v132:{en:"I'm a bit overwhelmed right now.", jp:"今ちょっといっぱいいっぱいだ。"},
  v133:{en:"It felt awkward to say no.", jp:"断るのは気まずかった。"},
  v134:{en:"He earns a decent salary.", jp:"彼はまともな給料を稼いでいる。"},
  v135:{en:"You look gorgeous tonight.", jp:"今夜のあなたはとても素敵だ。"},
  v136:{en:"Learning a language is tough but rewarding.", jp:"言語学習は大変だが報われる。"},
  v137:{en:"There's a tiny problem with the plan.", jp:"その計画にはごく小さな問題がある。"},
  v138:{en:"I had a weird dream last night.", jp:"昨夜は変な夢を見た。"},
  v139:{en:"Don't be scared; it's just a test.", jp:"怖がらないで、ただのテストだよ。"},
  v140:{en:"We're proud of what we built.", jp:"私たちは作り上げたものを誇りに思う。"},

  v141:{en:"Let's address this issue right away.", jp:"この問題にすぐ取り組もう。"},
  v142:{en:"Could you do me a small favor?", jp:"ちょっとお願いを聞いてくれる?"},
  v143:{en:"We're behind on the deadline.", jp:"締め切りに遅れている。"},
  v144:{en:"I'd like to make an appointment.", jp:"予約を取りたいのですが。"},
  v145:{en:"Attitude matters more than talent.", jp:"才能より態度が大事だ。"},
  v146:{en:"We're working on a tight budget.", jp:"厳しい予算でやりくりしている。"},
  v147:{en:"Old habits are hard to break.", jp:"古い習慣はなかなか直らない。"},
  v148:{en:"Music can change your mood.", jp:"音楽は気分を変えられる。"},
  v149:{en:"Being tall is an advantage in basketball.", jp:"バスケでは背が高いと有利だ。"},
  v150:{en:"First impressions are important.", jp:"第一印象は大切だ。"},
  v151:{en:"Opportunities like this are rare.", jp:"こんな機会はめったにない。"},
  v152:{en:"Let's assess the situation calmly.", jp:"状況を冷静に見極めよう。"},
  v153:{en:"Thank you for your quick response.", jp:"迅速なご返答ありがとうございます。"},
  v154:{en:"Let's schedule a call for Monday.", jp:"月曜に通話の予定を入れよう。"},
  v155:{en:"Your effort really paid off.", jp:"あなたの努力は本当に報われた。"},
  v156:{en:"We're making steady progress.", jp:"着実に進展している。"},
  v157:{en:"Thanks for the advice.", jp:"アドバイスありがとう。"},
  v158:{en:"Give me one good reason.", jp:"もっともな理由を1つ挙げて。"},
  v159:{en:"Give it a chance.", jp:"一度試してみて。"},
  v160:{en:"Travel gives you new experiences.", jp:"旅は新しい経験を与えてくれる。"},

  v161:{en:"Actually, that's a good point.", jp:"実は、それはいい指摘だね。"},
  v162:{en:"Basically, we just need to start.", jp:"要は、始めればいいだけだ。"},
  v163:{en:"Eventually, things got better.", jp:"最終的には、状況は良くなった。"},
  v164:{en:"Honestly, I'm not sure.", jp:"正直、よく分からない。"},
  v165:{en:"It'll probably be fine.", jp:"たぶん大丈夫だよ。"},
  v166:{en:"That's definitely worth trying.", jp:"それは間違いなく試す価値がある。"},
  v167:{en:"We barely made it in time.", jp:"かろうじて間に合った。"},
  v168:{en:"I hardly know him.", jp:"彼のことはほとんど知らない。"},
  v169:{en:"Have you seen him lately?", jp:"最近、彼に会った?"},
  v170:{en:"Instead of complaining, let's act.", jp:"文句を言う代わりに、行動しよう。"},
  v171:{en:"Anyway, thanks for coming.", jp:"とにかく、来てくれてありがとう。"},
  v172:{en:"We'll figure it out somehow.", jp:"どうにかして解決するよ。"},
  v173:{en:"Write it down; otherwise you'll forget.", jp:"メモして、じゃないと忘れるよ。"},
  v174:{en:"Meanwhile, please wait here.", jp:"その間、ここで待っていてください。"},
  v175:{en:"Apparently, the store is closed today.", jp:"どうやら今日は店が閉まっているらしい。"},

  v176:{en:"That reminds me of my hometown.", jp:"それで故郷を思い出すよ。"},
  v177:{en:"Which one do you prefer?", jp:"どっちの方が好き?"},
  v178:{en:"We expect good weather tomorrow.", jp:"明日は良い天気が予想される。"},
  v179:{en:"You promised you'd help.", jp:"手伝うって約束したよね。"},
  v180:{en:"I wonder if she's okay.", jp:"彼女は大丈夫かな。"},
  v181:{en:"Please consider it carefully.", jp:"よく検討してください。"},
  v182:{en:"I need time to prepare.", jp:"準備する時間が必要だ。"},
  v183:{en:"I'll handle the rest.", jp:"残りは私が対処するよ。"},
  v184:{en:"Nothing can replace hard work.", jp:"努力に代わるものはない。"},
  v185:{en:"I completed the course last week.", jp:"先週その講座を修了した。"},
  v186:{en:"I want to improve my listening.", jp:"リスニングを上達させたい。"},
  v187:{en:"Avoid making the same mistake.", jp:"同じミスは避けよう。"},
  v188:{en:"They don't allow photos inside.", jp:"館内は撮影禁止だ。"},
  v189:{en:"May I suggest another option?", jp:"別の選択肢を提案してもいい?"},
  v190:{en:"Did I mention I'm moving?", jp:"引っ越すって言ったっけ?"},
  v191:{en:"I didn't notice the sign.", jp:"その標識に気づかなかった。"},
  v192:{en:"I can't manage this on my own.", jp:"これは一人ではこなせない。"},
  v193:{en:"We can't afford to fail.", jp:"失敗する余裕はない。"},
  v194:{en:"You can always rely on family.", jp:"家族はいつでも頼れる。"},
  v195:{en:"Let's focus on what matters.", jp:"大事なことに集中しよう。"},
  v196:{en:"She insisted on doing it herself.", jp:"彼女は自分でやると言い張った。"},
  v197:{en:"I appreciate your patience.", jp:"辛抱強く待ってくれて感謝します。"},
  v198:{en:"Don't blame others for your choices.", jp:"自分の選択を人のせいにしないで。"},
  v199:{en:"I decided to quit smoking.", jp:"タバコをやめることにした。"},
  v200:{en:"Take a deep breath and relax.", jp:"深呼吸してリラックスして。"},
};
